# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: proxyhub
    binary: proxyhub
    main: ./cmd/proxyhub
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: proxynode
    binary: proxynode
    main: ./cmd/proxynode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: zip

changelog:
  disable: '{{ envOrDefault "IS_SNAPSHOT" "false" }}'
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  disable: '{{ envOrDefault "IS_SNAPSHOT" "false" }}'
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

kos:
  - id: proxyhub
    build: proxyhub
    repositories:
      - ghcr.io/tarik02/proxyhub/proxyhub
    tags:
      - '{{ .Version }}'
      - '{{ if eq .Branch "next" }}next{{end}}'
      - '{{ if not .Prerelease }}stable{{end}}'
    platforms:
      - linux/amd64
      - linux/arm64
    bare: true

  - id: proxynode
    build: proxynode
    repositories:
      - ghcr.io/tarik02/proxyhub/proxynode
    tags:
      - '{{ .Version }}'
      - '{{ if eq .Branch "next" }}next{{end}}'
      - '{{ if not .Prerelease }}stable{{end}}'
    platforms:
      - linux/amd64
      - linux/arm64
    bare: true
