// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v6.33.0
// source: pb/pbclient/default.proto

package pbclient

import (
	pb "github.com/tarik02/proxyhub/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProxiesRequest) Reset() {
	*x = WatchProxiesRequest{}
	mi := &file_pb_pbclient_default_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProxiesRequest) ProtoMessage() {}

func (x *WatchProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbclient_default_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProxiesRequest.ProtoReflect.Descriptor instead.
func (*WatchProxiesRequest) Descriptor() ([]byte, []int) {
	return file_pb_pbclient_default_proto_rawDescGZIP(), []int{0}
}

type ProxyEventInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxy         []*pb.Proxy            `protobuf:"bytes,1,rep,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyEventInit) Reset() {
	*x = ProxyEventInit{}
	mi := &file_pb_pbclient_default_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyEventInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEventInit) ProtoMessage() {}

func (x *ProxyEventInit) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbclient_default_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEventInit.ProtoReflect.Descriptor instead.
func (*ProxyEventInit) Descriptor() ([]byte, []int) {
	return file_pb_pbclient_default_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyEventInit) GetProxy() []*pb.Proxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

type ProxyEventAdd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxy         *pb.Proxy              `protobuf:"bytes,1,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyEventAdd) Reset() {
	*x = ProxyEventAdd{}
	mi := &file_pb_pbclient_default_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyEventAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEventAdd) ProtoMessage() {}

func (x *ProxyEventAdd) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbclient_default_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEventAdd.ProtoReflect.Descriptor instead.
func (*ProxyEventAdd) Descriptor() ([]byte, []int) {
	return file_pb_pbclient_default_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyEventAdd) GetProxy() *pb.Proxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

type ProxyEventUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxy         *pb.Proxy              `protobuf:"bytes,1,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyEventUpdate) Reset() {
	*x = ProxyEventUpdate{}
	mi := &file_pb_pbclient_default_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyEventUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEventUpdate) ProtoMessage() {}

func (x *ProxyEventUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbclient_default_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEventUpdate.ProtoReflect.Descriptor instead.
func (*ProxyEventUpdate) Descriptor() ([]byte, []int) {
	return file_pb_pbclient_default_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyEventUpdate) GetProxy() *pb.Proxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

type ProxyEventDel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyEventDel) Reset() {
	*x = ProxyEventDel{}
	mi := &file_pb_pbclient_default_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyEventDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEventDel) ProtoMessage() {}

func (x *ProxyEventDel) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbclient_default_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEventDel.ProtoReflect.Descriptor instead.
func (*ProxyEventDel) Descriptor() ([]byte, []int) {
	return file_pb_pbclient_default_proto_rawDescGZIP(), []int{4}
}

func (x *ProxyEventDel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProxyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ProxyEvent_Init
	//	*ProxyEvent_Add
	//	*ProxyEvent_Update
	//	*ProxyEvent_Del
	Event         isProxyEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyEvent) Reset() {
	*x = ProxyEvent{}
	mi := &file_pb_pbclient_default_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEvent) ProtoMessage() {}

func (x *ProxyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbclient_default_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEvent.ProtoReflect.Descriptor instead.
func (*ProxyEvent) Descriptor() ([]byte, []int) {
	return file_pb_pbclient_default_proto_rawDescGZIP(), []int{5}
}

func (x *ProxyEvent) GetEvent() isProxyEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ProxyEvent) GetInit() *ProxyEventInit {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *ProxyEvent) GetAdd() *ProxyEventAdd {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_Add); ok {
			return x.Add
		}
	}
	return nil
}

func (x *ProxyEvent) GetUpdate() *ProxyEventUpdate {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *ProxyEvent) GetDel() *ProxyEventDel {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_Del); ok {
			return x.Del
		}
	}
	return nil
}

type isProxyEvent_Event interface {
	isProxyEvent_Event()
}

type ProxyEvent_Init struct {
	Init *ProxyEventInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type ProxyEvent_Add struct {
	Add *ProxyEventAdd `protobuf:"bytes,2,opt,name=add,proto3,oneof"`
}

type ProxyEvent_Update struct {
	Update *ProxyEventUpdate `protobuf:"bytes,3,opt,name=update,proto3,oneof"`
}

type ProxyEvent_Del struct {
	Del *ProxyEventDel `protobuf:"bytes,4,opt,name=del,proto3,oneof"`
}

func (*ProxyEvent_Init) isProxyEvent_Event() {}

func (*ProxyEvent_Add) isProxyEvent_Event() {}

func (*ProxyEvent_Update) isProxyEvent_Event() {}

func (*ProxyEvent_Del) isProxyEvent_Event() {}

var File_pb_pbclient_default_proto protoreflect.FileDescriptor

var file_pb_pbclient_default_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x62, 0x2e,
	0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x10, 0x70, 0x62, 0x2f, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x31, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x69, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x05, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x22, 0x30, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x41, 0x64, 0x64, 0x12, 0x1f, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52,
	0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x22, 0x33, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x22, 0x1f, 0x0a, 0x0d, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xe1, 0x01, 0x0a,
	0x0a, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x04, 0x69,
	0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x70,
	0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x2e,
	0x0a, 0x03, 0x61, 0x64, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62,
	0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x48, 0x00, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x37,
	0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x70, 0x62, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x03, 0x64, 0x65, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c,
	0x48, 0x00, 0x52, 0x03, 0x64, 0x65, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x32, 0x56, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x62,
	0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50,
	0x72, 0x6f, 0x78, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x72, 0x69, 0x6b, 0x30, 0x32, 0x2f, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x68, 0x75, 0x62, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pb_pbclient_default_proto_rawDescOnce sync.Once
	file_pb_pbclient_default_proto_rawDescData []byte
)

func file_pb_pbclient_default_proto_rawDescGZIP() []byte {
	file_pb_pbclient_default_proto_rawDescOnce.Do(func() {
		file_pb_pbclient_default_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_pbclient_default_proto_rawDesc), len(file_pb_pbclient_default_proto_rawDesc)))
	})
	return file_pb_pbclient_default_proto_rawDescData
}

var file_pb_pbclient_default_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_pbclient_default_proto_goTypes = []any{
	(*WatchProxiesRequest)(nil), // 0: pb.pbclient.WatchProxiesRequest
	(*ProxyEventInit)(nil),      // 1: pb.pbclient.ProxyEventInit
	(*ProxyEventAdd)(nil),       // 2: pb.pbclient.ProxyEventAdd
	(*ProxyEventUpdate)(nil),    // 3: pb.pbclient.ProxyEventUpdate
	(*ProxyEventDel)(nil),       // 4: pb.pbclient.ProxyEventDel
	(*ProxyEvent)(nil),          // 5: pb.pbclient.ProxyEvent
	(*pb.Proxy)(nil),            // 6: pb.Proxy
}
var file_pb_pbclient_default_proto_depIdxs = []int32{
	6, // 0: pb.pbclient.ProxyEventInit.proxy:type_name -> pb.Proxy
	6, // 1: pb.pbclient.ProxyEventAdd.proxy:type_name -> pb.Proxy
	6, // 2: pb.pbclient.ProxyEventUpdate.proxy:type_name -> pb.Proxy
	1, // 3: pb.pbclient.ProxyEvent.init:type_name -> pb.pbclient.ProxyEventInit
	2, // 4: pb.pbclient.ProxyEvent.add:type_name -> pb.pbclient.ProxyEventAdd
	3, // 5: pb.pbclient.ProxyEvent.update:type_name -> pb.pbclient.ProxyEventUpdate
	4, // 6: pb.pbclient.ProxyEvent.del:type_name -> pb.pbclient.ProxyEventDel
	0, // 7: pb.pbclient.Service.WatchProxies:input_type -> pb.pbclient.WatchProxiesRequest
	5, // 8: pb.pbclient.Service.WatchProxies:output_type -> pb.pbclient.ProxyEvent
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pb_pbclient_default_proto_init() }
func file_pb_pbclient_default_proto_init() {
	if File_pb_pbclient_default_proto != nil {
		return
	}
	file_pb_pbclient_default_proto_msgTypes[5].OneofWrappers = []any{
		(*ProxyEvent_Init)(nil),
		(*ProxyEvent_Add)(nil),
		(*ProxyEvent_Update)(nil),
		(*ProxyEvent_Del)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_pbclient_default_proto_rawDesc), len(file_pb_pbclient_default_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_pbclient_default_proto_goTypes,
		DependencyIndexes: file_pb_pbclient_default_proto_depIdxs,
		MessageInfos:      file_pb_pbclient_default_proto_msgTypes,
	}.Build()
	File_pb_pbclient_default_proto = out.File
	file_pb_pbclient_default_proto_goTypes = nil
	file_pb_pbclient_default_proto_depIdxs = nil
}
