// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v6.30.2
// source: pb/pbhub/default.proto

package pbhub

import (
	pb "github.com/tarik02/proxyhub/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EgressWhitelist *pb.EgressWhitelist    `protobuf:"bytes,1,opt,name=egressWhitelist,proto3" json:"egressWhitelist,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_pb_pbhub_default_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbhub_default_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pb_pbhub_default_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetEgressWhitelist() *pb.EgressWhitelist {
	if x != nil {
		return x.EgressWhitelist
	}
	return nil
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_pb_pbhub_default_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbhub_default_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_pb_pbhub_default_proto_rawDescGZIP(), []int{1}
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_pb_pbhub_default_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbhub_default_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_pb_pbhub_default_proto_rawDescGZIP(), []int{2}
}

func (x *DisconnectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_pb_pbhub_default_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbhub_default_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_pb_pbhub_default_proto_rawDescGZIP(), []int{3}
}

type UpdatedEgressWhitelistRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EgressWhitelist *pb.EgressWhitelist    `protobuf:"bytes,1,opt,name=egressWhitelist,proto3" json:"egressWhitelist,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatedEgressWhitelistRequest) Reset() {
	*x = UpdatedEgressWhitelistRequest{}
	mi := &file_pb_pbhub_default_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedEgressWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedEgressWhitelistRequest) ProtoMessage() {}

func (x *UpdatedEgressWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbhub_default_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedEgressWhitelistRequest.ProtoReflect.Descriptor instead.
func (*UpdatedEgressWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_pb_pbhub_default_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatedEgressWhitelistRequest) GetEgressWhitelist() *pb.EgressWhitelist {
	if x != nil {
		return x.EgressWhitelist
	}
	return nil
}

type UpdatedEgressWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedEgressWhitelistResponse) Reset() {
	*x = UpdatedEgressWhitelistResponse{}
	mi := &file_pb_pbhub_default_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedEgressWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedEgressWhitelistResponse) ProtoMessage() {}

func (x *UpdatedEgressWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pbhub_default_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedEgressWhitelistResponse.ProtoReflect.Descriptor instead.
func (*UpdatedEgressWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_pb_pbhub_default_proto_rawDescGZIP(), []int{5}
}

var File_pb_pbhub_default_proto protoreflect.FileDescriptor

var file_pb_pbhub_default_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x68, 0x75, 0x62, 0x2f, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x2e, 0x70, 0x62, 0x68,
	0x75, 0x62, 0x1a, 0x10, 0x70, 0x62, 0x2f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0f, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x0f, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5e, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0f, 0x65, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x57, 0x68, 0x69,
	0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x0f, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf9, 0x01, 0x0a, 0x07, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x16,
	0x2e, 0x70, 0x62, 0x2e, 0x70, 0x62, 0x68, 0x75, 0x62, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x62, 0x68, 0x75,
	0x62, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x2e,
	0x70, 0x62, 0x2e, 0x70, 0x62, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x70, 0x62, 0x68, 0x75, 0x62, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x27, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x62, 0x68, 0x75, 0x62, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x70, 0x62,
	0x2e, 0x70, 0x62, 0x68, 0x75, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x45, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x72, 0x69, 0x6b, 0x30, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x68, 0x75, 0x62, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x68, 0x75, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pb_pbhub_default_proto_rawDescOnce sync.Once
	file_pb_pbhub_default_proto_rawDescData []byte
)

func file_pb_pbhub_default_proto_rawDescGZIP() []byte {
	file_pb_pbhub_default_proto_rawDescOnce.Do(func() {
		file_pb_pbhub_default_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_pbhub_default_proto_rawDesc), len(file_pb_pbhub_default_proto_rawDesc)))
	})
	return file_pb_pbhub_default_proto_rawDescData
}

var file_pb_pbhub_default_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_pbhub_default_proto_goTypes = []any{
	(*HelloRequest)(nil),                   // 0: pb.pbhub.HelloRequest
	(*HelloResponse)(nil),                  // 1: pb.pbhub.HelloResponse
	(*DisconnectRequest)(nil),              // 2: pb.pbhub.DisconnectRequest
	(*DisconnectResponse)(nil),             // 3: pb.pbhub.DisconnectResponse
	(*UpdatedEgressWhitelistRequest)(nil),  // 4: pb.pbhub.UpdatedEgressWhitelistRequest
	(*UpdatedEgressWhitelistResponse)(nil), // 5: pb.pbhub.UpdatedEgressWhitelistResponse
	(*pb.EgressWhitelist)(nil),             // 6: pb.EgressWhitelist
}
var file_pb_pbhub_default_proto_depIdxs = []int32{
	6, // 0: pb.pbhub.HelloRequest.egressWhitelist:type_name -> pb.EgressWhitelist
	6, // 1: pb.pbhub.UpdatedEgressWhitelistRequest.egressWhitelist:type_name -> pb.EgressWhitelist
	0, // 2: pb.pbhub.Service.Hello:input_type -> pb.pbhub.HelloRequest
	2, // 3: pb.pbhub.Service.Disconnect:input_type -> pb.pbhub.DisconnectRequest
	4, // 4: pb.pbhub.Service.UpdatedEgressWhitelist:input_type -> pb.pbhub.UpdatedEgressWhitelistRequest
	1, // 5: pb.pbhub.Service.Hello:output_type -> pb.pbhub.HelloResponse
	3, // 6: pb.pbhub.Service.Disconnect:output_type -> pb.pbhub.DisconnectResponse
	5, // 7: pb.pbhub.Service.UpdatedEgressWhitelist:output_type -> pb.pbhub.UpdatedEgressWhitelistResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_pbhub_default_proto_init() }
func file_pb_pbhub_default_proto_init() {
	if File_pb_pbhub_default_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_pbhub_default_proto_rawDesc), len(file_pb_pbhub_default_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_pbhub_default_proto_goTypes,
		DependencyIndexes: file_pb_pbhub_default_proto_depIdxs,
		MessageInfos:      file_pb_pbhub_default_proto_msgTypes,
	}.Build()
	File_pb_pbhub_default_proto = out.File
	file_pb_pbhub_default_proto_goTypes = nil
	file_pb_pbhub_default_proto_depIdxs = nil
}
