name: ci

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: jdx/mise-action@v2

      - if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' }}
        name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          # renovate: datasource=github-releases depName=semantic-release packageName=semantic-release/semantic-release
          semantic_version: 24.2.1
          extra_plugins: |
            @semantic-release/exec@6.0.3
