name: ci

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4

  next-pr:
    needs:
      - get-next-version

    if: ${{ github.ref == 'refs/heads/next' && needs.get-next-version.outputs.new-release-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Create/Update Pull Request
        run: |
          pr_title="release v${{ needs.get-next-version.outputs.new-release-version }}"
          pr_url="$(gh --repo "$REPO" pr list --base "$BASE_BRANCH" --head "$HEAD_BRANCH" --state open --limit 1 --json url --jq .[].url)"
          if [[ -z "${pr_url}" ]]; then
            gh --repo "$REPO" pr create -B "$BASE_BRANCH" -H "$HEAD_BRANCH" --title "$pr_title" --body ''
          else
            gh --repo "$REPO" pr edit "$pr_url" --title "$pr_title"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          BASE_BRANCH: ${{ github.event.repository.default_branch }}
          HEAD_BRANCH: ${{ github.ref_name }}

  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: jdx/mise-action@v2

      - if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' }}
        name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # renovate: datasource=github-releases depName=semantic-release packageName=semantic-release/semantic-release
          semantic_version: 24.2.1
          extra_plugins: |
            @semantic-release/exec@6.0.3
